export class Countries {
  countries = [
    { id: 124, name: 'Canada'},
    { id: 304, name: 'Greenland'},
    { id: 840, name: 'USA'},
    { id: 484, name: 'Mexico'},
    { id: 192, name: 'Cuba'},
    { id: 388, name: 'Jamaica'},
    { id: 44, name: 'Bahamas'},
    { id: 332, name: 'Haiti'},
    { id: 214, name: 'Dominican Republic'},
    { id: 630, name: 'Puerto Rico'},

    { id: 84, name: 'Belize'},
    { id: 320, name: 'Guatemala'},
    { id: 558, name: 'Nicaragua'},
    { id: 340, name: 'Honduras'},
    { id: 222, name: 'El Salvador'},
    { id: 591, name: 'Panama'},
    { id: 188, name: 'Costa Rica'},
    { id: 170, name: 'Columbia'},
    { id: 780, name: 'Trinidad and Tobago'},
    { id: 862, name: 'Venezuela'},
    { id: 328, name: 'Guyana'},
    { id: 740, name: 'Suriname'},
    { id: 218, name: 'Ecuador'},
    { id: 76, name: 'Brazil'},
    { id: 604, name: 'Peru'},
    { id: 68, name: 'Bolivia'},
    { id: 600, name: 'Paraguay'},
    { id: 858, name: 'Uruguay'},
    { id: 32, name: 'Argentina'},
    { id: 152, name: 'Chile'},

    { id: 643, name: 'Russia'},
    { id: 246, name: 'Finland'},
    { id: 578, name: 'Norway'},
    { id: 752, name: 'Sweden'},
    { id: 208, name: 'Denmark'},
    { id: 352, name: 'Iceland'},
    { id: 826, name: 'UK'},
    { id: 372, name: 'Ireland'},
    { id: 528, name: 'The Netherlands'},
    { id: 276, name: 'Germany'},
    { id: 442, name: 'Luxembourg'},
    { id: 56, name: 'Belgium'},
    { id: 250, name: 'France'},
    { id: 756, name: 'Switzerland'},
    { id: 724, name: 'Spain'},
    { id: 620, name: 'Portugal'},
    { id: 380, name: 'Italy'},
    { id: 40, name: 'Czechia'},
    { id: 203, name: 'Austria'},
    { id: 616, name: 'Poland'},
    { id: 440, name: 'Lithuania'},
    { id: 428, name: 'Latvia'},
    { id: 233, name: 'Estonia'},
    { id: 112, name: 'Belarus'},
    { id: 804, name: 'Ukraine'},
    { id: 498, name: 'Moldova'},
    { id: 643, name: 'Albania'},
    { id: 642, name: 'Romania'},
    { id: 100, name: 'Bulgaria'},
    { id: 300, name: 'Greece'},
    { id: 807, name: 'North Macedonia'},
    { id: 688, name: 'Serbia'},
    { id: -2, name: 'Kosovo'},
    { id: 499, name: 'Montenegro'},
    { id: 70, name: 'Bosnia and Hertzegovina'},
    { id: 191, name: 'Croatia'},
    { id: 705, name: 'Slovenia'},
    { id: 348, name: 'Hungary'},
    { id: 703, name: 'Slovakia'},
    { id: 196, name: 'Cyprus'},

    { id: 792, name: 'Turkey'},
    { id: 124, name: 'Georgia'},
    { id: 31, name: 'Azerbaijan'},
    { id: 246, name: 'Armenia'},
    { id: 422, name: 'Lebanon'},
    { id: 478, name: 'Syria'},
    { id: 376, name: 'Israel'},
    { id: 275, name: 'Palestine'},
    { id: 682, name: 'Saudi Arabia'},
    { id: 887, name: 'Yemen'},
    { id: 512, name: 'Oman'},
    { id: 784, name: 'United Arab Emirates'},
    { id: 634, name: 'Qatar'},
    { id: 414, name: 'Kuwait'},
    { id: 368, name: 'Iraq'},
    { id: 364, name: 'Iran'},

    { id: 4, name: 'Afghanistan'},
    { id: 586, name: 'Pakistan'},
    { id: 356, name: 'India'},
    { id: 795, name: 'Turkmenistan'},
    { id: 860, name: 'Uzbekistan'},
    { id: 762, name: 'Tajikistan'},
    { id: 417, name: 'Kyrgyzstan'},
    { id: 398, name: 'Kazakhstan'},
    { id: 496, name: 'Mongolia'},
    { id: 156, name: 'China'},
    { id: 408, name: 'North Korea'},
    { id: 410, name: 'South Korea'},
    { id: 392, name: 'Japan'},
    { id: 524, name: 'Nepal'},
    { id: 64, name: 'Bhutan'},
    { id: 50, name: 'Bangladesh'},
    { id: 104, name: 'Myanmar'},
    { id: 144, name: 'Sri Lanka'},
    { id: 764, name: 'Thailand'},
    { id: 418, name: 'Laos'},
    { id: 116, name: 'Cambodia'},
    { id: 704, name: 'Vietnam'},
    { id: 458, name: 'Malaysia'},
    { id: 158, name: 'Taiwan'},

    { id: 104, name: 'Philippines'},
    { id: 104, name: 'Bhunei'},
    { id: 360, name: 'Indonesia'},
    { id: 626, name: 'East Timor'},
    { id: 458, name: 'Malaysia'},
    { id: 90, name: 'Solomon Islands'},
    { id: 548, name: 'Vanuatu'},
    { id: 242, name: 'Fiji'},
    { id: 598, name: 'Papau New Guinea'},
    { id: 36, name: 'Australia'},
    { id: 554, name: 'New Zealand'},

    { id: 12, name: 'Algeria'},
    { id: 788, name: 'Tunisia'},
    { id: 504, name: 'Morocco'},
    { id: 478, name: 'Mauritania'},
    { id: 434, name: 'Libya'},
    { id: 818, name: 'Egypt'},
    { id: 729, name: 'Sudan'},
    { id: 148, name: 'Chad'},
    { id: 562, name: 'Niger'},
    { id: 466, name: 'Mali'},
    { id: 686, name: 'Senegal'},
    { id: 270, name: 'Gambia'},
    { id: 624, name: 'Guinea Bissau'},
    { id: 694, name: 'Sierra Leone'},
    { id: 430, name: 'Liberia'},
    { id: 384, name: 'Ivory Coast'},
    { id: 854, name: 'Burkina Faso'},
    { id: 288, name: 'Ghana'},
    { id: 768, name: 'Togo'},
    { id: 204, name: 'Benin'},
    { id: 566, name: 'Nigeria'},
    { id: 120, name: 'Cameroon'},
    { id: 226, name: 'Equatorial Guinea'},
    { id: 266, name: 'Gabon'},
    { id: 178, name: 'Republic of Congo'},
    { id: 140, name: 'Central African Republic'},
    { id: 180, name: 'Democratic Republic of the Congo'},
    { id: 728, name: 'South Sudan'},
    { id: 232, name: 'Eritrea'},
    { id: 262, name: 'Djibouti'},
    { id: 231, name: 'Ethiopia'},
    { id: 706, name: 'Somalia'},
    { id: -3, name: 'Somalia'},
    { id: 404, name: 'Kenya'},
    { id: 646, name: 'Rwanda'},
    { id: 108, name: 'Burundi'},
    { id: 834, name: 'Tanzania'},
    { id: 508, name: 'Mozambique'},
    { id: 454, name: 'Malawi'},
    { id: 894, name: 'Zambia'},
    { id: 24, name: 'Angola'},
    { id: 516, name: 'Namibia'},
    { id: 710, name: 'South Africa'},
    { id: 426, name: 'Lesotho'},
    { id: 748, name: 'Etwatini'},
    { id: 72, name: 'Botswana'},
    { id: 716, name: 'Zimbabwe'},
    { id: 450, name: 'Madagascar'},

    { id: 238, name: 'Falkland Islands / Islas Malvinas'},
    { id: 260, name: 'French Southern and Antarctic Lands'},
    { id: 10, name: 'Antarctica'}
  ];
}
